s = 'TGCCCGAAAACCCGAATAATTATGTACGATGAGTTGGAGTGCGACATTCTAGTGGGCATACGCCATCTCCCGGGAATTTAGCGTTAGCCGGTTTGCAATGTTCAGCGCGATGAAAGGCATATAGTTAACATTCAAATGCGGTCTCGCGCTCTATTTTAGATCATCGAAGGGGCGAAGGCGCCTCGACAGCGCAGGTCAAATAGTAGAAGAAAGCTCGACACCATGGCAGTCGTCTGGATTGGGGACCTTGTCGCGCATTGCTAACAGCTGGAAGGATATAAGTACGATAGAGCCGCGGCCTCAAAAAGGGCTGGCATACCATGATAATCAAGCCCACGACATCTTTATGCGCTTGGTGCATCCTGACATAACTACTTCCTTCATAACGTGTTGCTACCGTTATCCTCCGGATTAGGTAGATAAGCGTTTAACGCCTCGGACAATTCGGGTGGAGAGACGTCAAGGCTTCAAGGTTAGTAAAGGTGTGAGTCACATTTACTTATTACTAAAATCGCGGATAAATACAACACCGCGGTACAGCTCGAGAACAATGCTGCGGCGTCAGACTGCGAATACATACCCTTCATGTCCCAGGCATTGTGTGTGCCCCCATGGCCTTTCTAAACGAACCTAGGTACTTAATCGAAGGTTAAGGGCAAGCCTCTGAAAGGAACCATAGTGAACTGTTGAACGTGAGAGGCTAGCTAAGATTCCGAAACTCATGACTGATCCAGGGTTTTGTGATGATTTGGTACTCGAAACCCCACATGCTTCCTGTAGATTTTGCTCTTCCGTTCACAGCGTAGCCATGCTAACCCGTCATTCTGCTCTTTGTAAGCGTAGTGATTCAGGCGAAGAAGACTGAGAGAACCGTTGATCAATAGGCCTCAATTCTGATGTCCTAACGCCTGGCCCATATTGAGCCTCAAATGAGATTAGGCGACAAGGGGAACGGATCGCTACACATTAAA'
Acount = 0
Gcount = 0
Ccount = 0
Tcount = 0
n = len(s)
for i in range (n):
    if s[i] =="A":
        Acount +=1
    if s[i] =="G":
        Gcount +=1
    if s[i] =="C":
        Ccount +=1
    if s[i] =="T":
        Tcount +=1



A = str (Acount)
C = str(Ccount)
G = str(Gcount)
T = str (Tcount)



print A + " " + C + " "+ G + " " + T 
    


 
 
 
  
